table 'Time Periods'
	lineageTag: fdbe931b-8558-4713-8210-2f2a6d29a798

	measure 'Date Filter' = ```
			
			VAR SelectedPeriod = SELECTEDVALUE('Time Periods'[Period])
			VAR StartDate = 
			    SWITCH(
			        SelectedPeriod,
			        "Last 12 Months", TODAY() - 365,
			        "Q1 2025", DATE(2025,1,1),
			        "Q4 2024", DATE(2024,10,1),
			        "Custom Range", MIN('QualitestData'[StartDate])
			    )
			VAR EndDate = 
			    SWITCH(
			        SelectedPeriod,
			        "Last 12 Months", TODAY(),
			        "Q1 2025", DATE(2025,3,31),
			        "Q4 2024", DATE(2024,12,31),
			        "Custom Range", MAX('QualitestData'[EndDate])
			    )
			
			VAR CurrentDate = MAX('Calendar'[Date])  -- Add this line
			RETURN
			    IF(
			        CurrentDate >= StartDate && CurrentDate <= EndDate,
			        1,
			        0
			    )
			```
		formatString: 0
		lineageTag: f33493c7-3125-41b5-8503-864119f6e6ed

	column Period
		lineageTag: 5436ea45-2d34-42c4-b37d-f29b8954866b
		summarizeBy: none
		isNameInferred
		sourceColumn: [Period]

		annotation SummarizationSetBy = Automatic

	column SortOrder
		formatString: 0
		lineageTag: 3125f06c-7b0b-4d0b-bf6e-bdc1415f5094
		summarizeBy: sum
		isNameInferred
		sourceColumn: [SortOrder]

		annotation SummarizationSetBy = Automatic

	partition 'Time Periods' = calculated
		mode: import
		source =
				
				DATATABLE(
				    "Period", STRING,
				    "SortOrder", INTEGER,
				    {
				        {"Last 12 Months", 1},
				        {"Q1 2025", 2},
				        {"Q2 2025", 3},
				        {"Custom Range", 4}
				    }
				)

	annotation PBI_Id = 7da2fe64a2ce427f84ac0379687e0f7e

